application: portfolio
version: 1
runtime: php
threadsafe: no
api_version: 1

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.txt$dev
- ^(.*/)?.*\.psd$
- ^(.*/)?.*\.db$
- ^.*django/.*
- ^.*demo/.*
- ^(.*/)?\.hg.*

inbound_services:
- mail

builtins:
- deferred: on
- remote_api: on


handlers:

- url: /
  script: index.php

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /fonts
  static_dir: fonts 

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico 