application: skillful-eon-815
version: 1
runtime: php55
threadsafe: no
api_version: 1

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.txt$dev
- ^(.*/)?.*\.psd$
- ^(.*/)?.*\.db$
- ^.*django/.*
- ^.*demo/.*
- ^(.*/)?\.hg.*

inbound_services:
- mail

builtins:
- deferred: on
- remote_api: on

handlers:

- url: /
  script: index.php
  
- url: /index.php
  script: index.php
  
- url: /email.php
  script: email.php
  
- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /fonts
  static_dir: fonts 

- url: /download
  static_dir: download

- url: /bower_components
  static_dir: bower_components

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico 

- url: /fonts/(.*\.ttf)
  static_files: fonts/\1
  upload: fonts/(.*\.ttf)
  mime_type: application/x-font-ttf

- url: /fonts/(.*\.otf)
  static_files: fonts/\1
  upload: fonts/(.*\.otf)
  mime_type: font/opentype

- url: /fonts/(.*\.eot)
  static_files: fonts/\1
  upload: fonts/(.*\.eot)
  mime_type: application/vnd.ms-fontobject

- url: /fonts/(.*\.woff)
  static_files: fonts/\1
  upload: fonts/(.*\.woff)
  mime_type: application/x-font-woff